version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: logiflow-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - logiflow-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: logiflow-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - logiflow-rabbitmq-data:/var/lib/rabbitmq

volumes:
  logiflow-db-data:
  logiflow-rabbitmq-data:
