spring.application.name=graphql-gateway
server.port=${SERVER_PORT:8080}

# Habilitar GraphiQL (interfaz web de pruebas en http://localhost:8080/graphiql)
spring.graphql.graphiql.enabled=true
# Habilitar soporte de WebSockets para suscripciones GraphQL
spring.graphql.websocket.path=/graphql

# Configuración RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:}

# Direcciones de Microservicios Backend (REST)
pedidos.service.url=${PEDIDOS_SERVICE_URL:http://localhost:8085}
ruteo.service.url=${RUTEO_SERVICE_URL:http://localhost:8086}
