spring.application.name=graphql-gateway
server.port=8080

# Habilitar GraphiQL (interfaz web de pruebas en http://localhost:8080/graphiql)
spring.graphql.graphiql.enabled=true
# Habilitar soporte de WebSockets para suscripciones GraphQL
spring.graphql.websocket.path=/graphql

# Configuración RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Direcciones de Microservicios Backend (REST)
pedidos.service.url=http://localhost:8085
ruteo.service.url=http://localhost:8086
