apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logiflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # REST - Fase 1/Fase 2
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: ms-auth
                port:
                  number: 8083
          - path: /api/clientes
            pathType: Prefix
            backend:
              service:
                name: ms-clientes
                port:
                  number: 8084
          - path: /api/pedidos
            pathType: Prefix
            backend:
              service:
                name: ms-pedidos
                port:
                  number: 8085
          - path: /api/ruteo
            pathType: Prefix
            backend:
              service:
                name: ms-ruteo
                port:
                  number: 8086
          - path: /api/vehiculos
            pathType: Prefix
            backend:
              service:
                name: ms-flota-rest
                port:
                  number: 8081
          - path: /api/conductores
            pathType: Prefix
            backend:
              service:
                name: ms-flota-rest
                port:
                  number: 8081

          # SOAP - ms-taller-soap. Preserva /ws y /ws/taller.wsdl.
          - path: /ws/taller.wsdl
            pathType: Exact
            backend:
              service:
                name: ms-taller-rest
                port:
                  number: 8082
          - path: /ws/seguimiento
            pathType: Prefix
            backend:
              service:
                name: ms-seguimiento
                port:
                  number: 8087
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: ms-taller-rest
                port:
                  number: 8082

          # GraphQL HTTP, GraphiQL y GraphQL subscriptions por WebSocket.
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graphql-gateway
                port:
                  number: 8080
          - path: /graphiql
            pathType: Prefix
            backend:
              service:
                name: graphql-gateway
                port:
                  number: 8080
