apiVersion: v1
kind: Secret
metadata:
  name: logiflow-secrets
type: Opaque
stringData:
  POSTGRES_USER: replace_with_postgres_user
  POSTGRES_PASSWORD: replace_with_postgres_password
  RABBITMQ_DEFAULT_USER: replace_with_rabbitmq_user
  RABBITMQ_DEFAULT_PASS: replace_with_rabbitmq_password
  JWT_SECRET: replace_with_64_char_random_jwt_secret
