spring.application.name=ms-seguimiento
server.port=${SERVER_PORT:8087}

# Configuración RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:}
