spring.application.name=ms-ruteo
server.port=8086

# Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/logiflow_ruteo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# URLs de Microservicios Colaboradores (REST)
flota.service.url=http://localhost:8081
pedidos.service.url=http://localhost:8085

# Documentacion OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
